version: "3.7"

services:
  peer:
    image: hyperledger/fabric-peer:1.4.3
    networks:
      hlf:
        aliases:
          - ${PEER_HOSTNAME}.${PEER_DOMAIN}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=${FABRIC_LOGGING_SPEC}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=${PEER_HOSTNAME}.${PEER_DOMAIN}
      - CORE_PEER_ADDRESS=${PEER_HOSTNAME}.${PEER_DOMAIN}:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=${PEER_HOSTNAME}.${PEER_DOMAIN}:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${PEER_HOSTNAME}.${PEER_DOMAIN}:7051
      - CORE_PEER_LOCALMSPID=${CORE_PEER_LOCALMSPID}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}
    volumes:
      - /var/run/:/host/var/run/
      - msp:/etc/hyperledger/fabric/msp
      - tls:/etc/hyperledger/fabric/tls
      - data:/var/hyperledger/production
    ports:
      - ${PORT}:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

volumes:
  msp:
    name: ${PEER_HOSTNAME}.${PEER_DOMAIN}.msp
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDR}"
      device: ":${NFS_PATH}/crypto-config/peerOrganizations/${PEER_DOMAIN}/peers/${PEER_HOSTNAME}.${PEER_DOMAIN}/msp"
  tls:
    name: ${PEER_HOSTNAME}.${PEER_DOMAIN}.tls
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDR}"
      device: ":${NFS_PATH}/crypto-config/peerOrganizations/${PEER_DOMAIN}/peers/${PEER_HOSTNAME}.${PEER_DOMAIN}/tls"
  data:
    name: ${PEER_HOSTNAME}.${PEER_DOMAIN}.data

networks:
  hlf:
    name: ${NETWORK}
    external: true
