### health
GET http://localhost:8080/health
Accept: application/vnd.alkaid.v1+xml

### initialize
POST http://localhost:8080/initialize
Content-Type: application/json

{
  "id": "root",
  "name": "root",
  "email": "root@alkaid.com",
  "password": "root"
}

### login by id or email.
POST http://localhost:8080/login
Content-Type: application/json

{
  "id": "{{username}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body.token); %}

### get user by id.
GET http://localhost:8080/users/root
Authorization: Bearer {{auth_token}}

###