### 健康检测接口
GET http://localhost:8080/health
Accept: application/vnd.alkaid.v0+xml

### 系统初始化接口
POST http://localhost:8080/initialize
Content-Type: application/json

{
  "id": "root",
  "name": "root",
  "email": "root@alkaid.com",
  "password": "root"
}

### 登陆接口，支持 username 和 email
POST http://localhost:8080/login
Content-Type: application/json

{
  "id": "{{username}}",
  "password": "{{password}}"
}

> {% client.global.set("auth_token", response.body.token); %}

### 注册用户接口
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": "org1admin",
  "organizationId": "org1",
  "name": "admin",
  "email": "user1@org1.com",
  "password": "org1admin",
  "transactionPassword": "123456",
  "role": "organization"
}

### 查询用户信息接口
GET http://localhost:8080/users/root@alkaid.com
Authorization: Bearer {{auth_token}}

###